name: clang-format

on:
  push:
    paths-ignore:
      - 'README.md'
      - 'doc/**'
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'doc/**'

jobs:
  clang-format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: |
          clang-format --version
          clang-format --dump-config

      - uses: DoozyX/clang-format-lint-action@v0.20
        with:
          extensions: 'hpp,cpp'
          clangFormatVersion: 20
