name: clang-tidy

on:
  push:
    paths-ignore:
      - 'README.md'
      - 'doc/**'
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'doc/**'

permissions:
  contents: read

jobs:
  clang-tidy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v7

    - name: Install Dependencies
      run: |
        sudo apt-get -qq update -yq
        sudo apt-get -qq install -y clang-tidy --no-install-recommends --no-install-suggests

    - name: Generate Compilation Database
      run: cmake -S . -B build -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_EXPORT_COMPILE_COMMANDS=ON

    - name: Run clang-tidy on configured sources and included PEGTL headers
      continue-on-error: true
      run: run-clang-tidy -p build -quiet -j "$(nproc)" -header-filter='(^|/)include/tao/'
