name: msys2

on:
  push:
    paths-ignore:
      - 'README.md'
      - 'doc/**'
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'doc/**'

permissions:
  contents: read

jobs:
  msys2:
    strategy:
      fail-fast: false
      matrix:
        platform:
          - 'UCRT64'
          - 'CLANG64'
        build_type: [Debug, Release]

    defaults:
      run:
        shell: msys2 {0}

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - uses: msys2/setup-msys2@v2
      with:
        msystem: ${{matrix.platform}}
        pacboy: >-
          cc:p
          cmake:p
          ninja:p
        update: true

    - run: cmake -S . -B build -GNinja -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}

    - run: cmake --build build

    - run: ctest --test-dir build --output-on-failure
