name: Sanitizer

on:
  push:
    paths-ignore:
      - 'README.md'
      - 'doc/**'
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'doc/**'

permissions:
  contents: read

jobs:
  sanitizer:
    strategy:
      fail-fast: false
      matrix:
        cxx: [g++, clang++]
        sanitizer: [address, undefined]

    runs-on: ubuntu-latest

    env:
      CXX: ${{ matrix.cxx }}

    steps:
    - uses: actions/checkout@v4

    - run: cmake -S . -B build -GNinja -DCMAKE_BUILD_TYPE=Debug -DPEGTL_BUILD_EXAMPLES=OFF -DCMAKE_CXX_FLAGS="-fsanitize=${{ matrix.sanitizer }} -fno-sanitize-recover=undefined"

    - run: cmake --build build

    - run: ctest --test-dir build --output-on-failure
